// Decompiled with JetBrains decompiler
// Type: LcDevPack_TeamDamonA.Tools.FlagList
// Assembly: LcDevPack_TeamDamonA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 6B9BC8BF-B510-4945-A515-04135CC0F4A4
// Assembly location: C:\Users\NTServer\Desktop\LcDevPack_TeamDamonA\LcDevPack_TeamDamonA\LcDevPack_TeamDamonA.exe

namespace LcDevPack_TeamDamonA.Tools
{
  public class FlagList
  {
        public static string[] ZoneFlag = new string[64]
        {
              "0 ZONE_START",
              "1 ZONE_DUNGEON1",
              "2 ZONE_SINGLE_DUNGEON1",
              "3 ZONE_DUNGEON2",
              "4 ZONE_DRATAN",
              "5 ZONE_SINGLE_DUNGEON2",
              "6 ZONE_SINGLE_DUNGEON_TUTORIAL",
              "7 ZONE_MERAC",
              "8 ZONE_GUILDROOM",
              "9 ZONE_DUNGEON3",
              "10 ZONE_SINGLE_DUNGEON3",
              "11 ZONE_SINGLE_DUNGEON4",
              "12 ZONE_DUNGEON4",
              "13 ZONE_FREE_PK_DUNGEON",
              "14 ZONE_OXQUIZROOM",
              "15 ZONE_EGEHA",
              "16 ZONE_EGEHA_PK",
              "17 ZONE_EGEHA_DUNGEON_1",
              "18 ZONE_EGEHA_DUNGEON_8",
              "19 ZONE_EGEHA_DUNGEON_9",
              "20 ZONE_EGEHA_DUNGEON_10",
              "21 ZONE_DRATAN_CASTLE_DUNGEON",
              "22 ZONE_COMBO_DUNGEON",
              "23 ZONE_STREIANA",
              "24 ZONE_DRATAN_PK",
              "25 ZONE_EXTREME_CUBE",
              "26 ZONE_SPIRIT_CAVE",
              "27 ZONE_QUANIAN_CAVE",
              "28 ZONE_GOLEM_CAVE",
              "29 ZONE_EBONY_MINE",
              "30 ZONE_MISTY_CANYON",
              "31 ZONE_FLORAIM_CAVE",
              "32 ZONE_MONDSHINE",
              "33 ZONE_CAPELLA_1",
              "34 ZONE_CAPELLA_2",
              "35 ZONE_ALTER_OF_DARK",
              "36 ZONE_AKAN_TEMPLE",
              "37 ZONE_TRIVIA_CANYON",
              "38 ZONE_ROYAL_RUMBLE",
              "39 ZONE_TARIAN",
              "40 ZONE_BLOODYMIR",
              "41 ZONE_TARIAN_DUNGEON",
              "42 ZONE_RVR",
              "43 ",
              "44 ",
              "45 ",
              "46 ",
              "47 ",
              "48 ",
              "49 ",
              "50 ",
              "51 ",
              "52 ",
              "53 ",
              "54 ",
              "55 ",
              "56 ",
              "57 ",
              "58 ",
              "59 ",
              "60 ",
              "61 ",
              "62 ",
              "63 "
        };

        public static string[] Skills = new string[19]
    {
      "Singlemode",
      "Help",
      "Not Help",
      "Abstime",
      "Not Duplicate",
      "No Cancel",
      "Combo",
      "Logout",
      "Instant",
      "Guild",
      "Infinite",
      "Zone",
      "Summon Npc",
      "Not Bless",
      "ItemSkill",
      "Not Boss",
      "Not Single",
      "Toggle",
      "PVP Remove"
    };
    public static string[] Skills2 = new string[8] //dethunter12 add
    {
      "DEATH",
      "WEAPON",
      "SITDOWN",
      "PEACEZONE",
      "SHIELD",
      "STAND",
      "DARKNESS",
      "NO_COOL_TIME"  
    };
    public static string[] Skills3 = new string[16] //dethunter12 add
    {
        "APP_CHARACTER",
        "APP_FIRE",
        "APP_WIND",
        "APP_EARTH",
        "APP_WATER",
        "APP_HELLOUND",
        "APP_ELENEN",
        "APP_APET",
        "USE_CHARACTER",
        "USE_FIRE",
        "USE_WIND",
        "USE_EARTH",
        "USE_WATER",
        "USE_HELLOUND",
        "USE_ELENEN",
        "USE_APET"
    };
    public static string[] Npcs = new string[31]
    {
      "Shopper",
      "First Attack",
      "Attack",
      "Moving",
      "Peaceful",
      "Zonemover",
      "Castle Guard",
      "Refiner",
      "Quest",
      "Castle Tower",
      "Mineral",
      "Crops",
      "Eneergy",
      "Eternal",
      "Lord Symbol",
      "Remission",
      "Event",
      "Guard",
      "Keeper",
      "Guild",
      "MBoss",
      "Boss",
      "Resetstat",
      "Change Weapon",
      "Warcastle",
      "Display Map",
      "Quest Collect",
      "Party",
      "Raid",
      "Subcity",
      "Chaocity"
    };
    public static string[] Npcs1 = new string[12]
    {
      "Tradeagent",
      "Collsion",
      "Factory",
      "Trigger Choice",
      "Trigger Kill",
      "Npc Portal",
      "Dont Attack",
      "Affinity",
      "Shadow",
      "Crafting",
      "Totem Item",
      "Multi Exchange"
    };
    public static string[] NpcsAI = new string[4]
    {
      "Normal",
      "Tanker",
      "Damage Dealer",
      "Healer"
    };
    public static string[] SpecialSkills = new string[11]
    {
      "Mining",
      "Gathering",
      "Charge",
      "Stone",
      "Plant",
      "Element",
      "Make Weapon",
      "Make Wear",
      "Make G B",
      "Make Armor",
      "Make H S"
    };
    public static string[] ItemsEP4 = new string[64]
    {
      "Count",
      "Drop",
      "Upgrade",
      "Exchange",
      "Trade",
      "Not Delete",
      "Made",
      "Mix",
      "Cash",
      "Lord",
      "No Stash",
      "Change",
      "Composite",
      "Duplication",
      "lent",
      "Rare",
      "ABS",
      "Not Reform",
      "ZoneMove Del",
      "Origin",
      "Trigger",
      "Raid Special",
      "Quest",
      "Box",
      "Not TradeAgent",
      "Durability",
      "Costume2",
      "Socket",
      "Seller",
      "Castillan",
      "LetsParty",
      "Non-RVR",
      "Quest Give",
      "Toggle",
      "Compose",
      "NotSingle",
      "Invisible Custom",
      "37 ",
      "38 ",
      "39 ",
      "40 ",
      "41 ",
      "42 ",
      "43 ",
      "44 ",
      "45 ",
      "46 ",
      "47 ",
      "48 ",
      "49 ",
      "50 ",
      "51 ",
      "52 ",
      "53 ",
      "54 ",
      "55 ",
      "56 ",
      "57 ",
      "58 ",
      "59 ",
      "60 ",
      "61 ",
      "62 ",
      "63 "
    };
    public static string[] ItemsEP3 = new string[37]
    {
      "Count",
      "Drop",
      "Upgrade",
      "Exchange",
      "Trade",
      "Not Delete",
      "Made",
      "Mix",
      "Cash",
      "Lord",
      "No Stash",
      "Change",
      "Composite",
      "Duplication",
      "lent",
      "Rare",
      "ABS",
      "Not Reform",
      "ZoneMove Del",
      "Origin",
      "Trigger",
      "Raid Special",
      "Quest",
      "Box",
      "Not TradeAgent",
      "Durability",
      "Costume2",
      "Socket",
      "Seller",
      "Castillan",
      "LetsParty",
      "Non-RVR",
      "Quest Give",
      "Toggle",
      "Compose",
      "NotSingle",
      "Invisible Custom"
    };
  }
}
